### ISSUE TITLE
Team canvas opstellen

### ISSUE THREAD

**Issue by Daan645** [Daan645/lose-your-head-the-client-case#1]
Wij willen een teamcanvas opstellen zodat we weten wat iedereens sterke en zwakke punten zijn, en hier vervolgens rekening mee houden.

**Comment by TomDeeterink1** [comment]
23-09-24

**Team canvas**

Met het team hebben we op dag 1 al gelijk de teamcanvas samen gesteld. Hier staan onze principes en waarden in, maar ook de doelen en skills van teammembers.


![Image](https://github.com/user-attachments/assets/39560ed7-12e5-4f85-909e-9b52867498a5)

**Comment by TomDeeterink1** [comment]
06-01-25

Team canvas

Met het team hebben we op dag 1 al gelijk de teamcanvas samen gesteld. Hier staan onze principes en waarden in, maar ook de doelen en skills van teammembers.
![Image](https://github.com/user-attachments/assets/45436462-2d7f-4b21-aeb1-5fea3eb810ec)
