### ISSUE TITLE
Ontwerp maken

### ISSUE THREAD

**Issue by Daan645** [Daan645/lose-your-head-the-client-case#10]
Maak / schets een ontwerp. Op basis van het aangeleverde figma bestand.

**Comment by driezie** [comment]
### Versie 1 design  (concept)

Met dit ontwerp laat je nu verschillende radio stations zien


![Image](https://github.com/user-attachments/assets/48b36ea6-7dd9-4831-8ae9-9a6d571070ae)

**Comment by rutgerkock** [comment]
Het is best veel om naar te kijken, maar overzicht bewaren is best wel goed gelukt. Een punt waar ik op zou letten is dat het moeilijk is om te zien waar je nu op de tijdlijn zit. De streep is vrij dun en er is geen grote stip/marker aan de bovenkant, dit is iets wat jullie kunnen proberen duidelijker zichtbaar te maken. Ook is de streep niet gecentreerd :(.

**Comment by driezie** [comment]
![Image](https://github.com/user-attachments/assets/06b287f9-6c7b-4597-bc35-041f1a043cac)

**Comment by Mossati** [comment]
Het is een beetje te druk in het schema, maak misschien gebruik van horizontale lijnen om wat verschil te creeëren voor de zenders.
Om wat meer ruimte te besparen probeer de titel en tijd van een programma onderelkaar plaatsen en niet zo veel wit ruimte als nu.
Het ontwerp ziet er voor de rest best wel goed uit.

**Comment by amirnapoletano** [comment]
Ik zou de tijd gaan centreren, omadt het duiderlijker is om te zien waar ik ben

**Comment by Jaywesterlow** [comment]
- Good design makes a product understandable
Het is een logische layout. Alhoewel ik even moest zoeken omdat ik niet wist op welke pagina ik was en omdat ik keek naar het eerste design waarbij het kleurgebruik een beetje overweldigend is. Goed aangepast en een logische layout

- Good design is thorough down to the last detail
Zover ik kan zien is het erg gedetailleerd. De lijn op de huidige tijd, de rode border om de actieve programmas

- Good design is as little design as possible
Het design is wel erg druk. Er is veel content waardoor ik het wel begrijp, maar probeer het anders in secties in te delen waardoor er minder focus ligt op op de sectie waar de gebruiker niet mee bezig is

**Comment by OniWithTheHoodie** [comment]
bron voor de tijdlijn/gids vanuit de ziggo website:

 ![Image](https://github.com/user-attachments/assets/3c51af7b-fe1c-4c5d-bba5-abc10176d063)
