### ISSUE TITLE
Standaard button component maken

### ISSUE THREAD

**Issue by Daan645** [Daan645/lose-your-head-the-client-case#16]
We willen een standaard button component maken die overal te hergebruiken is.
![Image](https://github.com/user-attachments/assets/b54d9a7e-8616-4a8f-8659-a60b7ce2e1af)

**Comment by Daan645** [comment]
# JS Test

Ik heb de button getest zonder javascript alles werkt aan de button behalve de klik animatie, dit is niet erg omdat dit een enhancement is!

**Comment by Daan645** [comment]
# Responsive test
De knop is responsive tot 300px en zelfs verder als het scherm kleiner wordt gaat de text weg en is er alleen nog het whatsapp logo.
<img width="302" alt="Scherm­afbeelding 2024-10-02 om 11 06 21" src="https://github.com/user-attachments/assets/ce81e7b3-e08e-4d03-9c30-9e92f1dfd1b9">

**Comment by Daan645** [comment]
# Browser test
Ik heb de button op de volgende browsers getest: Chrome, safari, arc en firefox 

- Arc
In arc werkte de knop naar behoren en zag ie er precies zo uit als ik hem gebouwd heb.
<img width="1783" alt="Scherm­afbeelding 2024-10-02 om 20 02 56" src="https://github.com/user-attachments/assets/c8c19c89-e215-4407-955b-1921c0b800a1">

- Safari
- op safari was ook alles precies hetzelfde!
<img width="700" alt="Scherm­afbeelding 2024-10-02 om 20 04 24" src="https://github.com/user-attachments/assets/eb912bdc-e62b-4069-9fb8-c3fe1aca9c1d">

- Firefox
Ook in firefox geen aanmerkingen
<img width="1781" alt="Scherm­afbeelding 2024-10-02 om 20 06 04" src="https://github.com/user-attachments/assets/b608649a-2a5e-45d3-8613-bf240a02a972">

- Chrome
Ook in chrome werkt alles goed
<img width="1190" alt="Scherm­afbeelding 2024-10-02 om 20 07 00" src="https://github.com/user-attachments/assets/74d66cf8-b5bf-4640-b1ff-31081f2082d4">

**Comment by Daan645** [comment]
# Lighthouse test

In mijn eerste lighthouse test had ik een een slechtere accesibility ik ben vervolgens een title element gaan toevoegen en dit heeft het verholpen. Ook had ik slechte peformance, dit kwam door een javascript animatie functie. Ik had hier een klik animatie gemaakt alleen voegde deze eigenlijk niet zoveel toe

**Comment by TomDeeterink1** [comment]
He @Daan645 je button is nog niet helemaal ready. Ik pas hem even aan.
