### ISSUE TITLE
MoSCoW labels maken

### ISSUE THREAD

**Issue by Daan645** [Daan645/lose-your-head-the-client-case#3]
Er moeten moscow labels gemaakt worden zodat we weten welke taken voorrang hebben.

**Comment by TomDeeterink1** [comment]
MoSCoW labels zijn klaar voor gebruik.

Deze kan je hier vinden:

![Image](https://github.com/user-attachments/assets/17bf6c9b-b0bf-4110-9e51-09d03a9a6063)
![Image](https://github.com/user-attachments/assets/9fda2697-cd91-4916-9a84-3255869ec78e)
