### ISSUE TITLE
Sprintreview / Sprintreview voorbereiden.

### ISSUE THREAD

**Issue by Daan645** [Daan645/lose-your-head-the-client-case#55]
We willen van te voren bedenken wat we gaan aankaarten en laten zien tijdens de sprintreview.

**Comment by Daan645** [comment]
# Opdrachtgever op de hoogte stellen
We hebben een mail opgesteld waarmee we de opdrachtgever alvast op de hoogte hebben gehouden wat wij graag willen bespreken in de sprintreview, zodat de opdrachtgever zich hier alvast rekening mee kan houden.

<img width="1437" alt="Scherm­afbeelding 2024-10-14 om 15 42 15" src="https://github.com/user-attachments/assets/4790ecbb-919c-4192-9d26-177a813255f2">

**Comment by Daan645** [comment]
# Voorbereiding presentatie sprintreview

## Ontwerp wijzigingen
- Horizontale view op desktop
Wij hebben gekozen voor een horizontale view op dekstop zodat je meer radiostations op een pagina kan zien, zo hoeft de gebruiker minder te zoeken en kan de gebruiker alles in een oogopslag zien. Ook is het handiger omdat een desktop vaak meer pixels in de breedte heeft dan in de lengte dit scheelt scrollen.

- Blauwe knoppen
De roze kleur is erg opvallend en druk deze willen we graag alleen op de knoppen zetten die iemand aanroepen tot actie (call to action) zoals de app studio knop.

## Wat hebben wij gemaakt en hoe werkt het?

- Header en mobile menu
We hebben een header gebouwt die in een mobile menu veranderd wanneer het scherm kleiner wordt

- Button component
Call to action button om de studio te appen met leuke micro interaction op hover

- Tabs menu
Hiermee kun je op alle andere tabjes komen

- Tijdsoverzicht
In de tijdsoverzicht kan je zien welke dj op welke tijd speelt deze schalen mee met de tijd hoe langer de show hoe langer de card.

- Footer
We hebben een responsive footer gemaakt met alle socials en links.

- Wat willen we nog maken
de uren buttons
de tijdlijn
sorteren van programmas
radio shows van een bepaalde dag ophalen

- Dingen waar we tegen aan lopen
De kleurcontrast van het blauw en roze met wit is niet goed, is hier ruimte in om deze kleuren donkerder te maken?
Moet de detail pagina ook uitgewerkt worden

- Dingen waar wij beoordeeld op willen worden
Design keuzes
Uitwerking
Code
Heeft u nog ideeën op of aanmerkingen?


## Rol verdeling

- Tom presentator
- Lesley eigen deel presenteren
- Jelte tijdbewaarder
- Daan Notaris

**Comment by driezie** [comment]
design
hoe de site eruit ziet
eventeel meer vertellen over code

**Comment by Daan645** [comment]
# Voorbereiding presentatie sprintreview

## Ontwerp wijzigingen
- Horizontale view op desktop
Op het originele design is maar een station te zien, we vonden het handig om meer radio stations naast elkaar te zetten. Als inspiratie hebben we ziggo app gebruikt.

- Blauwe knoppen
We hebben de roze knoppen geprobeert maar dat werdt te druk naar onze mening.

## Wat hebben wij gemaakt en hoe werkt het?

- Header en mobile menu Button component
De header zit erin met een whatsapp knop zodat de gebruikers de studio kunnen appen
Als het menu klein wordt krijg je het mobile menu erbij, als je er op klikt krijg je een leuke laad animatie wat de ervaring meer smooth maakt.

- Button component
Je kan de button aanpassen met variabelen zodat deze altijd aanpasbaar is.

- Tabs menu
We hebben een menu gebouwt waarmee je alle dagen van de maand kan zien waarmee de huidige dag active wordt ook kun je doormiddel van de knoppen naar links en rechts. Ook zit er een fade effect in.

- Tijdsoverzicht
We hebben een overzicht gemaakt waarmee je de huidige shows kunt zien en de shows die erna komen. Graag zouden wij de huidige shows vooraan kunnen zien.

Opdrachtgever: daar heb je een JS functie voor dat heet scroll into. Je kan deze ook in je onmount zetten zodat ze altijd naar de actieve shows scrollen als de pagina inlaad

- Footer
We hebben een responsive footer gemaakt met alle socials en links.

- Mediaplayer
De kleuren en de uitlijningen moet nog aangepast worden en we willen de huidige dj erin laten tonen. Op mobiel wordt de mediaplayer kleiner. Ik wil hem zo maken als ze erop klikken dat de player ene overlay krijgt

Opdrachtgever: Ik vind dat een goed idee dat hebben we nu ook alleen dit moet wel alleen maar op mobiel werken. Alles zit wel dicht op elkaar tussen het bovenste blokje en eerder op veronica, ook zou ik de lijnen centreren.

- Desktop
Zodra de website groter wordt wordt alles uitgerekt en groter.

- Overig
We hebben ook een media player gebouwt deze is nog niet volledig af 

- Ons doel voor deze sprint was de ui compleet te hebben en de functionaliteit van de tijdlijn bouwen

- Wat willen we nog maken
We willen buttons maken om te zoeken, de tijdlijn uitbreiden, en het sorteren van de programma's

Opdracht gever: in welk opzicht sorteren?
Op tijdzone en radio dj.

Opdrachtgever: leuk idee.

- Tips van opdracht gever:
We hebben nu een tijdsindicatie met een lijntje, die zou ik er wel graag in willen hebben want dan is het duidelijker waar je bent. Ik vind de dag selectie toffer dan wat wij nu hebben.

- Dingen waar we tegen aan lopen
Wij hebben wat testen gegaan lighthouse en peformance gingen goed hadden testen boven de 90%, De kleuren hebben geen goed contrast, aangezien dit de huisstijl is kunnen wij dit aanpassen of moeten wij dit voor lief nemen.

Opdrachtgever:
Dit is de verantwoordelijkheid van het mediahuis en daar kunnen wij alleen advies op geven

Dit kunnen wij doen doomiddel van een issue


Wat willen we bouwen 
- We willen graag een detail pagina bouwen voor de djs

Opdrachtgever: ik vind dat een leuk idee een modal lijkt me ook een tof idee maar ik laat het aan jullie over.

- overige vragen
Moet de huisstijl aanpasbaar zijn naar andere huisstijlen van de radiostations

Als jullie er tijd voor hebben zou het tof zijn maar het hoeft niet.

Ik vind het tof dat jullie een heel ander design hebben gebouwd dat vind ik echt cool.

**Comment by OniWithTheHoodie** [comment]
Feedback Nills.

Media player 

![Image](https://github.com/user-attachments/assets/3108979b-2a51-46fa-a8dd-30b7adb413f1)

- buttons centreren
- Roze tekst "Nu" en de tijd de lijnen met kleine streepjes centreren
