### ISSUE TITLE
Component Library Structure bedenken

### ISSUE THREAD

**Issue by TomDeeterink1** [Daan645/lose-your-head-the-client-case#77]
Wij willen een Component Library Structure bedenken voor onze site, hierna willen wij onze site hier in rebuilden.

**Comment by TomDeeterink1** [comment]
## Waarom een Component Library Structure?

### 1. Herbruikbaarheid

  Een component library bevat afzonderlijke, gestandaardiseerde componenten die in meerdere projecten of delen van een applicatie opnieuw kunnen worden gebruikt. Dit vermindert duplicatie en versnelt de ontwikkelingscyclus.
  
### 2. Consistentie

Het zorgt ervoor dat de gebruikersinterface consistent is door dezelfde componenten overal te gebruiken. Dit verbetert de gebruikerservaring (UX) en voorkomt visuele afwijkingen.

### 3. Efficiëntie

Door een goede structuur te hebben binnen een project kan je componenten sneller herbruiken. Hierdoor verloopt het project soepeler dan dat je alles apart zou bouwen.


## Welke keuzes hebben we?

**Comment by Daan645** [comment]
# Bronnen
Uitleg over atomic design: https://www.youtube.com/watch?v=Yi-A20x2dcA
