### ISSUE TITLE
Setup project

### ISSUE THREAD

**Issue by driezie** [Daan645/lose-your-head-the-client-case#9]

**Comment by TomDeeterink1** [comment]
Project is niet correct opgezet, libary voor componenten staan niet klaar.
Ook is de static nog niet ready, en is de root met kleuren nog niet gedaan.

Volgende keer iemand laten controleren voordat hij op done gaat,

Thanks

**Comment by TomDeeterink1** [comment]
Thanks @driezie , beter zo!
